### ISSUE TITLE
Linux ARM Not finding libLabJackM.so

### ISSUE THREAD

**Issue by mwilkens** [chrisJohn404/LabJack-nodejs#15]
Attempting to run this library on a Raspberry Pi 2 (ARMv7) isn't working correctly, likely due to a linking issue.

I've got the LabJackM library installed in the default location (/usr/local/lib/libLabJackM.so), and I've also added arm to the ljm-ffi.js defaultLinuxLibraryLoc object (and a few other objects across the project).

I'm still getting essentially a 'file not found' error.

`Failed to link function Internal_LJM_OpenAll { Error: ENOENT: no such file or directory, open 'libLabJackM.so'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at fs.readFileSync (fs.js:502:33)
    at new DynamicLibrary (/home/pi/calibTest/node_modules/ffi/lib/dynamic_library.js:67:21)
    at Object.Library (/home/pi/calibTest/node_modules/ffi/lib/library.js:45:12)
    at /home/pi/calibTest/node_modules/ljm-ffi/lib/ljm-ffi.js:963:50
    at Array.forEach (native)
    at loadLJMMultiple (/home/pi/calibTest/node_modules/ljm-ffi/lib/ljm-ffi.js:944:23)
    at Object.exports.load (/home/pi/calibTest/node_modules/ljm-ffi/lib/ljm-ffi.js:1037:5)
    at Object.<anonymous> (/home/pi/calibTest/node_modules/labjack-nodejs/lib/driver_wrapper.js:21:15)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'libLabJackM.so' }
`

If I hard-code the library's location into ljm-ffi.js I get a Dynamic Linking error, but essentially it's the same file not found issue. Here's that error:

`Failed to link function Internal_LJM_OpenAll Error: Dynamic Linking Error: /usr/local/lib/libLabJackM.so: cannot open shared object file: No such file or directory
    at new DynamicLibrary (/home/pi/calibTest/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.DynamicLibrary (/home/pi/calibTest/node_modules/ffi/lib/dynamic_library.js:33:12)
    at /home/pi/calibTest/node_modules/ljm-ffi/lib/ljm-ffi.js:969:50
    at Array.forEach (native)
    at loadLJMMultiple (/home/pi/calibTest/node_modules/ljm-ffi/lib/ljm-ffi.js:949:23)
    at Object.exports.load (/home/pi/calibTest/node_modules/ljm-ffi/lib/ljm-ffi.js:1043:5)
    at Object.<anonymous> (/home/pi/calibTest/node_modules/labjack-nodejs/lib/driver_wrapper.js:21:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
`

**Comment by chrisJohn404** [comment]
I don't know how simple or hard this issue will be to debug but I wanted to let you know that I am looking into your issue.  It looks like you are using a Raspberry Pi 2.  What version of nodejs are you using?  I believe Raspbian ships with a fairly old version of nodejs and i'm not sure how reliable two of the dependencies (ffi and ref) are on some of the older versions.  You can check this by typing "node -v" into the command line.

I recommend first upgrading your version of node (if possible) to something in the 4.x.x (LTS release) -> 6.x.x (fast moving...) range.  I used 0.10.x (which I believe is distributed with Raspbian) for a long time and it should still work, I just haven't tried it in a while.  I can downgrade and check if you want me to.  The best blog post that I have seen for installing node on Raspberry Pis is here:
https://blog.wia.io/installing-node-js-on-a-raspberry-pi-3

Node.js has been releasing official RPi builds in versions 4.x.x and higher.  I believe you should use the ARMv7 for the Pi2.  You also need to use the ARMv7 build for Pi3 due to the Raspbian OS currently being distributed (feel free to correct me if I am wrong).  Link to Node.js downloads page:
https://nodejs.org/en/download/current/

I have a feeling that LJM itself isn't properly installed on the Pi.  Were you able to compile and run the C examples?  I can post instructions on how to do that if you don't know how.  Our naming schemes are a little weird for what versions work on Raspberry Pis.  You should use the 'Linux armhf' version.  You should install and use the latest beta version.  A direct link to the .tar.gz file:
https://labjack.com/sites/default/files/software/LabJackM-1.1200-Raspbian-Linux-armhf-beta.tar.gz

I'll boot up a Pi2 and make sure this is all in working condition.  I verified that the latest beta version of LJM and the ljm-ffi library worked properly on a Pi3 but didn't try using the LabJack-nodejs wrapper.

**Comment by mwilkens** [comment]
I'm using Node.js 6.2.1

I've been using the Angstrom ARMv7 library (doh), which could explain the problem. I'll try it with the armhf version tomorrow morning when I have more time.

I'm also suspecting I may not have a dependency requirement after seeing this page https://labjack.com/support/what-are-system-requirements. Again, I'll get back to you tomorrow on that.

Regardless of whether or not this is a dumb mistake on my part it is worth noting that I had to modify the library to support the ARM architecture.

I appreciate the fast response ~ thanks!

**Comment by chrisJohn404** [comment]
You can definitely use the LJM library to control devices on all of the Raspberry Pis.  Kipling is another story.  It is built with nwjs (formerly node-webkit) instead of electron (which has official Raspberry Pi/arm support).  I/we at LabJack haven't had the time/resources to build and maintain a build for Raspberry Pis however that will hopefully change with the Pi3 and future Pis.  They have become fairly powerful devices.

What was the fix you had to make?  There are definitely a few switch statements floating around.  The code for allowing Nodejs to interact with .dll/.so libraries isn't 100% reusable across platforms and architectures.

**Comment by chrisJohn404** [comment]
Marking this complete because the ljm-ffi library now has the location for the LJM driver under the 'arm' option for the defaultLinusLibraryLoc.  Tested with raspberry pi 3, and the armhf version of the LJM library at version 1.1200.
